feat: adjustments on key generation

diff --git a/cosmospg/makefile b/cosmospg/makefile
--- a/cosmospg/makefile
+++ b/cosmospg/makefile
@@ -17,12 +17,11 @@ build:
 	@docker build -t $(IMAGE_NAME) .
 
 # Full test: Generate keys, initialize network, start network, wait, and then test the network
-full-test: generate-all-keys init-network start-network wait-for-network test-network
+full-test: clean generate-all-keys init-network start-network wait-for-network test-network
 
 wait-for-network:
 	@echo "Waiting for network to be ready..."
 	@sleep 30 # Waits for 30 seconds
-
 
 # Generate keys for a validator
 generate-keys:
@@ -30,49 +29,48 @@ generate-keys:
 		echo "No VALIDATOR_NAME provided. Exiting..."; \
 		exit 1; \
 	fi
-	@echo "Listing Current Keys for $(VALIDATOR_NAME)... "
-	@docker run --rm -it -v $(DOCKER_VOLUME_PATH)/$(VALIDATOR_NAME):/root/.simapp $(IMAGE_NAME) simd keys list --keyring-backend test
-
 	@echo "Generating keys for $(VALIDATOR_NAME)..."
-	@docker run --rm -v $(DOCKER_VOLUME_PATH)/$(VALIDATOR_NAME):/root/.simapp $(IMAGE_NAME) simd keys add $(VALIDATOR_NAME) --keyring-backend test
+	@docker run --rm -v $(DOCKER_VOLUME_PATH)/$(VALIDATOR_NAME):/root/.simapp $(IMAGE_NAME) sh -c \
+	"simd keys add $(VALIDATOR_NAME) --keyring-backend test > /root/.simapp/$(VALIDATOR_NAME)_output.txt && \
+	cat /root/.simapp/$(VALIDATOR_NAME)_output.txt | grep 'address:' | awk '{print \$$3}' > /root/.simapp/$(VALIDATOR_NAME)_address.txt"
 
-	@echo "Retrieving address for $(VALIDATOR_NAME)..."
-	@docker run --rm -v $(DOCKER_VOLUME_PATH)/$(VALIDATOR_NAME):/root/.simapp $(IMAGE_NAME) simd keys show $(VALIDATOR_NAME) -a --keyring-backend test
-
+	@echo "Address for $(VALIDATOR_NAME):"
+	@cat $(DOCKER_VOLUME_PATH)/$(VALIDATOR_NAME)/$(VALIDATOR_NAME)_address.txt || echo "Address file not found on host."
 
 # Generate keys for validator1 and validator2
 generate-all-keys:
 	$(MAKE) generate-keys VALIDATOR_NAME=validator1
 	$(MAKE) generate-keys VALIDATOR_NAME=validator2
+        # Create accounta and get its address
+	@echo "Creating account A ..."
+	$(MAKE) generate-keys VALIDATOR_NAME=accounta
 
 
 # Initialize the network
 init-network: clean generate-all-keys
 	@echo "Initializing network with 2 validators"
+	$(eval VALIDATOR1_ADDRESS=$(shell docker run --rm -v $(DOCKER_VOLUME_PATH)/$(VALIDATOR1_NAME):/root/.simapp --entrypoint cat $(IMAGE_NAME) /root/.simapp/$(VALIDATOR1_NAME)_address.txt | tr -d '\n'))
+	$(eval VALIDATOR2_ADDRESS=$(shell docker run --rm -v $(DOCKER_VOLUME_PATH)/$(VALIDATOR2_NAME):/root/.simapp --entrypoint cat $(IMAGE_NAME) /root/.simapp/$(VALIDATOR2_NAME)_address.txt | tr -d '\n'))
 
-	# Retrieve validator addresses directly from the keyring
-	$(eval VALIDATOR1_ADDRESS=$(shell docker run --rm -v $(DOCKER_VOLUME_PATH)/$(VALIDATOR1_NAME):/root/.simapp $(IMAGE_NAME) simd keys show $(VALIDATOR1_NAME) -a --keyring-backend test))
-	$(eval VALIDATOR2_ADDRESS=$(shell docker run --rm -v $(DOCKER_VOLUME_PATH)/$(VALIDATOR2_NAME):/root/.simapp $(IMAGE_NAME) simd keys show $(VALIDATOR2_NAME) -a --keyring-backend test))
-
-	# Initialize the genesis file and add genesis account for Validator 1
+        # Initialize the genesis file and add genesis account for Validator 1
 	@docker run --rm -v $(DOCKER_VOLUME_PATH)/$(VALIDATOR1_NAME):/root/.simapp $(IMAGE_NAME) simd init $(VALIDATOR1_NAME) --home /root/.simapp --chain-id $(CHAIN_ID)
 	@docker run --rm -v $(DOCKER_VOLUME_PATH)/$(VALIDATOR1_NAME):/root/.simapp $(IMAGE_NAME) simd genesis add-genesis-account $(VALIDATOR1_ADDRESS) $(GENESIS_ACCOUNT_AMOUNT) --home /root/.simapp --keyring-backend test
 
-	# Create gentx for Validator 1
+        # Create gentx for Validator 1
 	@docker run --rm -v $(DOCKER_VOLUME_PATH)/$(VALIDATOR1_NAME):/root/.simapp $(IMAGE_NAME) simd genesis gentx $(VALIDATOR1_NAME) $(GENESIS_ACCOUNT_AMOUNT) --home /root/.simapp --chain-id $(CHAIN_ID) --keyring-backend test
 
-	# Initialize the genesis file and add genesis account for Validator 2
+        # Initialize the genesis file and add genesis account for Validator 2
 	@docker run --rm -v $(DOCKER_VOLUME_PATH)/$(VALIDATOR2_NAME):/root/.simapp $(IMAGE_NAME) simd init $(VALIDATOR2_NAME) --home /root/.simapp --chain-id $(CHAIN_ID)
 	@docker run --rm -v $(DOCKER_VOLUME_PATH)/$(VALIDATOR2_NAME):/root/.simapp $(IMAGE_NAME) simd genesis add-genesis-account $(VALIDATOR2_ADDRESS) $(GENESIS_ACCOUNT_AMOUNT) --home /root/.simapp --keyring-backend test
 
-	# Create gentx for Validator 2
+        # Create gentx for Validator 2
 	@docker run --rm -v $(DOCKER_VOLUME_PATH)/$(VALIDATOR2_NAME):/root/.simapp $(IMAGE_NAME) simd genesis gentx $(VALIDATOR2_NAME) $(GENESIS_ACCOUNT_AMOUNT) --home /root/.simapp --chain-id $(CHAIN_ID) --keyring-backend test
 
-	# Collect gentxs and finalize the genesis file
+        # Collect gentxs and finalize the genesis file
 	@echo "Collecting gentxs..."
 	@docker run --rm -v $(DOCKER_VOLUME_PATH)/$(VALIDATOR1_NAME):/root/.simapp $(IMAGE_NAME) simd genesis collect-gentxs --home /root/.simapp
 
-	# Copy the final genesis file to both validators using Docker to avoid permission issues
+        # Copy the final genesis file to both validators using Docker to avoid permission issues
 	@echo "Copying the final genesis file to $(VALIDATOR2_NAME)"
 	@docker run --rm -v $(DOCKER_VOLUME_PATH):/data $(IMAGE_NAME) cp /data/$(VALIDATOR1_NAME)/config/genesis.json /data/$(VALIDATOR2_NAME)/config/genesis.json
 	@echo "Genesis file copied to $(VALIDATOR2_NAME)"
@@ -83,17 +81,24 @@ init-network: clean generate-all-keys
 
 # Test the network by creating an account, checking balances, performing a transaction, and checking balances again
 test-network:
-	# Create accounta and get its address
-	@echo "Creating accounta..."
-	$(eval ACCOUNT_A_ADDRESS=$(shell docker run --rm -v $(DOCKER_VOLUME_PATH)/accounta:/root/.simapp $(IMAGE_NAME) simd keys add csreaccount --home /root/.simapp --keyring-backend test | grep -o 'cosmos[[:alnum:]]*' | head -n 1))
-	@echo "accounta address: $(ACCOUNT_A_ADDRESS)"
+
+        # Load addresses from files
+	@echo "Loading Validator 1 address..."
+	$(eval VALIDATOR1_ADDRESS=$(shell cat $(DOCKER_VOLUME_PATH)/$(VALIDATOR1_NAME)/$(VALIDATOR1_NAME)_address.txt))
+	@echo "Validator 1 address: $(VALIDATOR1_ADDRESS)"
+
+	@echo "Loading Validator 2 address..."
+	$(eval VALIDATOR2_ADDRESS=$(shell cat $(DOCKER_VOLUME_PATH)/$(VALIDATOR2_NAME)/$(VALIDATOR2_NAME)_address.txt))
+	@echo "Validator 2 address: $(VALIDATOR2_ADDRESS)"
+	@echo "Loading Account A address..."
+	$(eval ACCOUNT_A_ADDRESS=$(shell cat $(DOCKER_VOLUME_PATH)/accounta/accounta_address.txt))
+	@echo "Account A address: $(ACCOUNT_A_ADDRESS)"
 
 	@if [ -z "$(ACCOUNT_A_ADDRESS)" ]; then \
 		echo "Error: Failed to retrieve accounta address"; \
 		exit 1; \
 	fi
-
-	# Check balance of the Genesis account
+        # Check balance of the Genesis account
 	@echo "Checking balance of the Genesis account..."
 	@docker run --rm -v $(DOCKER_VOLUME_PATH)/$(VALIDATOR1_NAME):/root/.simapp $(IMAGE_NAME) simd query bank balances $(VALIDATOR1_ADDRESS) --home /root/.simapp
 
@@ -127,4 +132,5 @@ stop-network:
 # Clean up the environment
 clean:
 	@echo "Cleaning up..."
-	@docker run --rm -v $(DOCKER_VOLUME_PATH):/data --user root $(IMAGE_NAME) rm -rf /data/* /data/*/* /data/*/*/*
+	@docker run --rm -v $(DOCKER_VOLUME_PATH):/data --entrypoint /bin/sh $(IMAGE_NAME) -c 'rm -rf /data/* /data/validator1/* /data/validator2/* /data/validator3/*'
+	@echo "Environment cleaned up."
